name: "ApproveOps - Approvals in IssueOps"
description: "IssueOps (ChatOps) workflows that require Approvals from someone in a designated GitHub team"

branding:
  icon: "user-check"
  color: "blue"

inputs:
  approve-command:
    description: "The command to look for in the comments; e.g.: /approve"
    required: true
    default: "/approve"
  team-name:
    description: "The name of the team in GitHub to check for the approval command; e.g.: approver-team"
    required: true
  token:
    description: "GitHub App installation token or PAT that has access to read the comments and check the org team's membership"
    required: true
    default: ${{ github.token }} # this doesn't allow tagging of the approval team; better to use GitHub App
  fail-if-approval-not-found:
    description: "Fail the action (i.e. show the action run as red) if the command is not found in the comments from someone in the approver team"
    required: true
    default: "true"
  post-successful-approval-comment:
    description: "Boolean whether to post successful approval comment"
    required: true
    default: "true"
  successful-approval-comment:
    description: "Comment to post if an approval is found"
    required: true
    default: ":tada:  You were able to run the workflow because someone left an approval in the comments!!"

outputs:
  approved:
    description: "Returns 'true' if the approval command was found in a comment from someone in the approver team, otherwise 'false'"

runs:
  using: "node20"
  main: "dist/index.js"
