env:
  node: true
  es2021: true
  jest: true

extends:
  - eslint:recommended

parserOptions:
  ecmaVersion: 12
  sourceType: commonjs

rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  no-console: warn
  prefer-const: error
  no-var: error