env:
  node: true
  es2021: true
  jest: true

extends:
  - eslint:recommended
  - plugin:prettier/recommended

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
  no-console: warn
  prefer-const: error
  no-var: error
